tests:
  - question_id: 301
    samples: 2
    template: "How many orders above 50000 are there from customers in the Engineering department in {{artifacts}}/{{qs_id}}/{{entity1}}.db? Create a JSON file {{artifacts}}/{{qs_id}}/big_orders_count.json that contains the answer using 'num_big_orders' as key."
    scoring_type: "readfile_jsonmatch"
    file_to_read: "{{artifacts}}/{{qs_id}}/big_orders_count.json"
    expected_content: "{\"num_big_orders\": {{sqlite_query:SELECT COUNT(*) FROM enterprise_orders o JOIN enterprise_customers c ON o.CUST_REF = c.CUST_ID WHERE c.DEPT_CD = 'Engineering' AND o.ORD_AMT > 50000:TARGET_FILE}}}"
    sandbox_setup:
      type: "create_sqlite"
      target_file: "{{artifacts}}/{{qs_id}}/{{entity1}}.db"
      content:
        tables:
          - name: "enterprise_customers"
            columns:
              - {name: "CUST_ID", type: "auto_id"}
              - {name: "CUST_NM", type: "TEXT", data_type: "person_name"}
              - {name: "DEPT_CD", type: "TEXT", data_type: "department"}
              - {name: "LOC_CD", type: "TEXT", data_type: "region"}
            rows: 20
          - name: "enterprise_orders"
            columns:
              - {name: "ORD_ID", type: "auto_id"}
              - {name: "CUST_REF", type: "INTEGER", foreign_key: "enterprise_customers.CUST_ID"}
              - {name: "ORD_AMT", type: "INTEGER", data_type: "currency"}
              - {name: "STAT_CD", type: "TEXT", data_type: "status"}
            rows: 75

  - question_id: 302
    samples: 2
    template: "How many orders above 50000 are there from customers in the Engineering department in {{artifacts}}/{{qs_id}}/{{entity1}}.db? Create a JSON file {{artifacts}}/{{qs_id}}/big_orders_count.txt that contains ONLY the answer"
    scoring_type: "readfile_stringmatch"
    file_to_read: "{{artifacts}}/{{qs_id}}/big_orders_count.txt"
    expected_content: "{{sqlite_query:SELECT COUNT(*) FROM enterprise_orders o JOIN enterprise_customers c ON o.CUST_REF = c.CUST_ID WHERE c.DEPT_CD = 'Engineering' AND o.ORD_AMT > 50000:TARGET_FILE}}"
    sandbox_setup:
      type: "create_sqlite"
      target_file: "{{artifacts}}/{{qs_id}}/{{entity1}}.db"
      content:
        tables:
          - name: "enterprise_customers"
            columns:
              - {name: "CUST_ID", type: "auto_id"}
              - {name: "CUST_NM", type: "TEXT", data_type: "person_name"}
              - {name: "DEPT_CD", type: "TEXT", data_type: "department"}
              - {name: "LOC_CD", type: "TEXT", data_type: "region"}
            rows: 20
          - name: "enterprise_orders"
            columns:
              - {name: "ORD_ID", type: "auto_id"}
              - {name: "CUST_REF", type: "INTEGER", foreign_key: "enterprise_customers.CUST_ID"}
              - {name: "ORD_AMT", type: "INTEGER", data_type: "currency"}
              - {name: "STAT_CD", type: "TEXT", data_type: "status"}
            rows: 75

  - question_id: 303
    samples: 2
    template: "How many orders above 50000 are there from customers in the Engineering department in {{artifacts}}/{{qs_id}}/{{entity1}}.db? Once you find the answer, reply in JSON format that contains the answer using 'num_big_orders' as key. REPLY ONLY WITH THE JSON itself, no other text or decoration!"
    scoring_type: "jsonmatch"
    expected_response: "{\"num_big_orders\": {{sqlite_query:SELECT COUNT(*) FROM enterprise_orders o JOIN enterprise_customers c ON o.CUST_REF = c.CUST_ID WHERE c.DEPT_CD = 'Engineering' AND o.ORD_AMT > 50000:TARGET_FILE}}}"
    sandbox_setup:
      type: "create_sqlite"
      target_file: "{{artifacts}}/{{qs_id}}/{{entity1}}.db"
      content:
        tables:
          - name: "enterprise_customers"
            columns:
              - {name: "CUST_ID", type: "auto_id"}
              - {name: "CUST_NM", type: "TEXT", data_type: "person_name"}
              - {name: "DEPT_CD", type: "TEXT", data_type: "department"}
              - {name: "LOC_CD", type: "TEXT", data_type: "region"}
            rows: 20
          - name: "enterprise_orders"
            columns:
              - {name: "ORD_ID", type: "auto_id"}
              - {name: "CUST_REF", type: "INTEGER", foreign_key: "enterprise_customers.CUST_ID"}
              - {name: "ORD_AMT", type: "INTEGER", data_type: "currency"}
              - {name: "STAT_CD", type: "TEXT", data_type: "status"}
            rows: 75

  - question_id: 304
    samples: 2
    template: "How many orders above 50000 are there from customers in the Engineering department in {{artifacts}}/{{qs_id}}/{{entity1}}.db? Once you determine the answer, REPLY WITH ONLY THE ANSWER and no other comment or punctuation or decoration. ONLY THE FINAL ANSWER"
    scoring_type: "stringmatch"
    expected_response: "{{sqlite_query:SELECT COUNT(*) FROM enterprise_orders o JOIN enterprise_customers c ON o.CUST_REF = c.CUST_ID WHERE c.DEPT_CD = 'Engineering' AND o.ORD_AMT > 50000:TARGET_FILE}}"
    sandbox_setup:
      type: "create_sqlite"
      target_file: "{{artifacts}}/{{qs_id}}/{{entity1}}.db"
      content:
        tables:
          - name: "enterprise_customers"
            columns:
              - {name: "CUST_ID", type: "auto_id"}
              - {name: "CUST_NM", type: "TEXT", data_type: "person_name"}
              - {name: "DEPT_CD", type: "TEXT", data_type: "department"}
              - {name: "LOC_CD", type: "TEXT", data_type: "region"}
            rows: 20
          - name: "enterprise_orders"
            columns:
              - {name: "ORD_ID", type: "auto_id"}
              - {name: "CUST_REF", type: "INTEGER", foreign_key: "enterprise_customers.CUST_ID"}
              - {name: "ORD_AMT", type: "INTEGER", data_type: "currency"}
              - {name: "STAT_CD", type: "TEXT", data_type: "status"}
            rows: 75
