# QwenSense Test Definitions
# Example test cases demonstrating different scoring types

tests:
  - question_id: 1
    samples: 2
    template: "Write the text 'Hello {{entity1}}!' inside this file: {{artifacts}}/{{entity2}}.txt"
    scoring_type: "readfile_stringmatch"
    file_to_read: "{{artifacts}}/{{entity2}}.txt"
    expected_content: 'Hello {{entity1}}!'
  
  - question_id: 2
    samples: 2
    template: "Create these files: {{entity1}}.log and {{entity2}}.config in the {{artifacts}} directory"
    scoring_type: "files_exist"
    files_to_check:
      - "{{artifacts}}/{{entity1}}.log"
      - "{{artifacts}}/{{entity2}}.config"
  
  - question_id: 3
    samples: 2
    template: "Respond with only this word: {{entity1}}"
    scoring_type: "stringmatch"
    expected_response: "{{entity1}}"
  
  - question_id: 4
    samples: 2
    template: "Create this directory structure inside the folder `{{artifacts}}`: {{expected_structure}}"
    scoring_type: "directory_structure"
    expected_structure:
      - "{{artifacts}}/{{entity1}}/"
      - "{{artifacts}}/{{entity1}}/{{entity2}}/"
      - "{{artifacts}}/{{entity1}}/logs/"
      - "{{artifacts}}/{{entity1}}/logs/{{entity3}}.log"
      - "{{artifacts}}/{{entity4}}/"
      - "{{artifacts}}/{{entity4}}/README.md"

  - question_id: 5
    samples: 2
    template: "Read the file {{artifacts}}/{{qs_id}}/{{entity1}}/notes.txt and tell me what line 3 says."
    scoring_type: "stringmatch"
    expected_response: "{{file_line:3:TARGET_FILE}}"
    sandbox_setup:
      type: "create_files"
      target_file: "{{artifacts}}/{{qs_id}}/{{entity1}}/notes.txt"
      content:
        type: "lorem_lines"
        count: 7

  - question_id: 6
    samples: 1  
    template: "What is the name of the first person in {{artifacts}}/{{qs_id}}/{{entity1}}/people.csv?"
    scoring_type: "stringmatch"
    expected_response: "{{csv_value:0:name:TARGET_FILE}}"
    sandbox_setup:
      type: "create_csv"
      target_file: "{{artifacts}}/{{qs_id}}/{{entity1}}/people.csv" 
      content:
        headers: ["name", "age", "city"]
        rows: 5